# Generated by Django 5.0.7 on 2024-08-10 16:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('obj_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=30)),
                ('birth_date', models.DateField(null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('role_at_shop', models.CharField(max_length=50)),
                ('owner_of_shop', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=255)),
                ('shop_description', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now)),
                ('subscription_detail', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
